export const SET_MEMBERS = 'SET_MEMBERS';
export const SET_MEMBER = 'SET_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const DELETE_MEMBER_FAILED = 'DELETE_MEMBER_FAILED';
export const MEMBERS_EMPTY = 'MEMBERS_EMPTY';
export const MEMBER_DELETED = 'MEMBER_DELETED';

export const FETCH_MEMBERS_FAILED = 'FETCH_MEMBERS_FAILED';
export const FETCH_MEMBERS_FINISHED = 'FETCH_MEMBERS_FINISHED';
export const ADD_MEMBER = 'ADD_PROJECT';
export const ADD_MEMBER_SUCCESS = 'ADD_PROJECT';
export const ADD_MEMBER_FAILED = 'ADD_PROJECT_FAILED';

export const SET_PROJECTS = 'SET_PROJECTS';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';
export const FETCH_PROJECTS_FINISHED = 'FETCH_PROJECTS_FINISHED';

export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT';
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED';
export const SET_PROJECT = 'SET_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';
export const PROJECTS_EMPTY = 'PROJECTS_EMPTY';
export const PROJECT_DELETED = 'PROJECT_DELETED';
