export const SET_MEMBERS = 'SET_MEMBERS';
export const FETCH_MEMBERS_FAILED = 'FETCH_MEMBERS_FAILED';

export const SET_PROJECTS = 'SET_PROJECTS';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';
