export const SET_MEMBERS = 'SET_MEMBERS';
export const FETCH_MEMBERS_FAILED = 'FETCH_MEMBERS_FAILED';
export const FETCH_MEMBERS_FINISHED = 'FETCH_MEMBERS_FINISHED';

export const SET_PROJECTS = 'SET_PROJECTS';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';
export const FETCH_PROJECTS_FINISHED = 'FETCH_PROJECTS_FINISHED';

export const ADD_PROJECT = 'ADD_PROJECT';
